import './globals.css';
import { ToastContainer } from 'react-toastify';
import 'react-toastify/dist/ReactToastify.css';

const inter = 'Inter'; // Replace with your actual font name or value

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}) {
  return (
    <html lang="en">
      <body className={inter}>
        <ToastContainer />
        {children}
      </body>
    </html>
  );
}
